# wrangler.toml
name = "gemini-proxy-panel2"
main = "src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "4ea9325108144e35817d7525933db1f9"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "4ea9325108144e35817d7525933db1f9"

